name: Wave Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Wave.zip
        run: |
          wget -O Wave.zip https://www.dropbox.com/s/gcwg085kk623k75/Wave.zip?dl=1

      - name: Extract Wave.zip
        run: unzip Wave.zip

      - name: Change Directory to Wave
        run: cd Wave

      - name: Run Wave.jar
        run: .jdk/bin/java -Xmx6G -server -jar Wave.jar
