name: Wave Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Wave.tar.gz
        run: |
          wget -O Wave.tar.gz https://www.dropbox.com/s/v0ahsx2bym8rgju/Wave.tar.gz?dl=1

      - name: Extract Wave.tar.gz
        run: tar -xzf Wave.tar.gz

      - name: Change Directory to Wave
        run: cd Wave

      - name: Run Wave.jar
        run: .jdk/bin/java -Xmx6G -server -jar Wave.jar
