name: minecraft

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up UFW and Java
      run: |
        sudo apt-get update
        sudo apt-get install ufw -y
        sudo ufw allow 25565
        sudo apt-get install openjdk-11-jdk -y
        sudo wget -O server.jar https://cdn.getbukkit.org/spigot/spigot-1.12.2.jar
        echo "eula=true" >> eula.txt
        

    - name: Run Minecraft Server
      run: |
        java -Xmx7G -Xms7G -jar server.jar nogui
