name: minecraft

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up UFW and Java
      run: |
        sudo apt-get update
        sudo apt-get install ufw -y
        sudo ufw allow 25565
        sudo apt-get install openjdk-11-jdk -y
      
    - name: Run Minecraft Server
      run: |
        java -Xmx15G -Xms15G -jar server.jar nogui

    - name: get ip
      run: |
        ip_address=$(curl -s https://2ip.ru/ | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
        echo "Your IP address: $ip_address"
        
    - name: hihihih test
      run: |
        while true; do
          echo "hihihih test"
          sleep 2
        done
