name: Install and Configure Pterodactyl

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker
      uses: actions/setup-docker@v2

    - name: Set up Pterodactyl
      run: |
        docker run -d -p 8080:8080 -p 2022:2022 -v /var/lib/pterodactyl:/data --name pterodactyl-panel quay.io/pterodactyl/core:latest

    - name: Wait for Pterodactyl to start
      run: sleep 30

    - name: Get Pterodactyl IP and Port
      run: |
        pterodactyl_ip=$(curl -s http://localhost:8080 | grep "auth-form" | grep -oE "([0-9]{1,3}\.){3}[0-9]{1,3}")
        pterodactyl_port=8000
        echo "Pterodactyl IP: $pterodactyl_ip"
        echo "Pterodactyl Port: $pterodactyl_port"
