name: SSH Access via Ngrok
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ngrok
        uses: w9jds/ngrok-action@v1
        with:
          authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}
          port: 22

      - name: Get Ngrok public URL
        id: ngrok
        run: echo ${{ steps.ngrok.outputs.url }}

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -H ${{ steps.ngrok.outputs.url }} >> ~/.ssh/known_hosts

      - name: SSH to Server
        run: |
          ssh -o "StrictHostKeyChecking=no" -p ${{ steps.ngrok.outputs.port }} root@${{ steps.ngrok.outputs.url }}
