name: Self-restart

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restart workflow
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
