name: minecraft

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up UFW
      run: |
        sudo apt-get install ufw -y
        sudo ufw enable

    - name: Check UFW status
      run: |
        sudo ufw status
        sudo ufw status numbered
