name: Build and Deploy Apache2 Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Apache2
      run: |
        sudo apt-get update
        sudo apt-get install -y apache2

    - name: Start Apache2 service
      run: |
        sudo systemctl start apache2

    - name: Install ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip

    - name: Expose port 3000 with ngrok
      run: |
        ./ngrok http 3000 --authtoken 1ud6OfzQ82xhLWIPmrc9I6ZprQX_6VWMX6VUaLCeafhtnrTzh

    - name: Get ngrok public URL
      id: ngrok_url
      run: |
        sleep 10
        curl --silent http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url' > ngrok_url.txt

    - name: Print ngrok public URL
      run: |
        cat ngrok_url.txt

    - name: Deploy Apache2 site
      run: |
        echo "Hello, Apache2!" | sudo tee /var/www/html/index.html
