name: Server

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update package lists
      run: sudo apt-get update

    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip

    - name: Open ngrok ports
      run: |
        ./ngrok authtoken 1ud6OfzQ82xhLWIPmrc9I6ZprQX_6VWMX6VUaLCeafhtnrTzh
        ./ngrok tcp 22 &
        ./ngrok tcp 2022 &

    - name: Set server name and change password
      run: |
        server_name=$(hostname)
        echo "Server name: $server_name"
        echo "root:219743956ra" | sudo chpasswd
        
    - name: Run print command
      run: |
        while true; do
          echo "Hello, world!"
          sleep 1
        done
