name: Install and Start DDRaceNetwork Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libfreetype6-dev libsqlite3-dev
          git clone https://github.com/ddnet/ddnet.git
          cd ddnet
          make

      - name: Start DDRaceNetwork Server
        run: |
          cd ddnet
          ./DDNet-Server &

      - name: Install Ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

      - name: Setup Ngrok and expose port
        run: |
          ./ngrok authtoken 1wrEftpedFU8eT91VOEGBiEj8XZ_2HTii1ryAoLfiiNoNYNUc
          ./ngrok tcp 8888
