name: Install and Run Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update packages
      run: sudo apt-get update

    - name: Install Java 11
      run: sudo apt-get install -y openjdk-11-jdk
      
    - name: Set up ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip

    - name: Authenticate ngrok
      run: ./ngrok authtoken 1wrEftpedFU8eT91VOEGBiEj8XZ_2HTii1ryAoLfiiNoNYNUc

    - name: Start ngrok and expose port
      run: |
        ./ngrok tcp 25565 --log=stdout > ngrok.log &

    - name: Wait for ngrok to starts
      run: sleep 10

    - name: Get ngrok URL
      run: |
        ngrok_url=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "Ngrok URL: $ngrok_url"

    - name: Create eula.txt
      run: |
        echo "eula=true" > eula.txt

    - name: Modify server.properties
      run: |
        echo "online-mode=false" >> server.properties

    - name: Install Spigot 1.12.2
      run: |
        wget https://cdn.getbukkit.org/spigot/spigot-1.12.2.jar -O server.jar
        
    - name: Display ngrok IP and port
      run: |
        ngrok_ip=$(echo $ngrok_url | awk -F/ '{print $3}' | awk -F: '{print $1}')
        ngrok_port=$(echo $ngrok_url | awk -F/ '{print $3}' | awk -F: '{print $2}')
        echo "Ngrok IP: $ngrok_ip"
        echo "Ngrok Port: $ngrok_port"

    - name: Start Minecraft Server
      run: java -Xmx7G -jar server.jar
