name: Self-restart with print

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run print command
        run: |
          while true; do
            echo "Hi world"
            sleep 1
          done

      - name: Restart workflow
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
