name: Wave Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Wave.zip
        run: |
          wget -O Wave.zip https://www.dropbox.com/s/gcwg085kk623k75/Wave.zip?dl=1

      - name: Install Java
        run: |
          wget https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.18%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.18_10.tar.gz
          tar xf OpenJDK11U-jdk_x64_linux_hotspot_11.0.18_10.tar.gz
          rm OpenJDK11U-jdk_x64_linux_hotspot_11.0.18_10.tar.gz
          rm /opt/jdk-11.0.18+10 -rf
          mv jdk-11.0.18+10 /opt

      - name: Set Java Version
        run: ln -svf /opt/jdk-11.0.18+10/bin/java /usr/bin/java

      - name: Extract Wave.zip
        run: unzip Wave.zip

      - name: Run Wave.jar
        run: java -Xmx6G -server -jar Wave.jar
