name: minecraft

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up UFW
      run: |
        sudo apt-get install ufw -y
        sudo ufw enable
        
    - name: Set up apache2
      run: |
        sudo apt-get install apache2 -y
        sudo ufw allow 80
        sudo ufw allow 8080
        
    - name: Get IP address
      run: |
        ip_address=$(curl -s https://2ip.ru/ | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
        echo "Your IP address: $ip_address"

    - name: Check UFW status
      run: |
        sudo ufw status
        sudo ufw status numbered
